FROM eclipse-temurin:17-jre-focal

EXPOSE 80

WORKDIR /app

# jar 파일 복사
COPY ./build/libs/em-saas-rest-api.jar /app/

ENTRYPOINT ["java", "-jar", "em-saas-rest-api.jar", "-Djava.net.preferIPv4Stack=true", "-Djava.net.preferIPv4Addresses=true"]