DELETE FROM em_stock.code;
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('AAC0000', 'AAC', '00', '00', '- AI 전자공시 조회 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('AAC0001', 'AAC', '00', '01', '긍정', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('AAC0002', 'AAC', '00', '02', '부정', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('AAC0003', 'AAC', '00', '03', '중립', 3);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('FSA0000', 'FSA', '00', '00', '- 종목별 안정성 차트 조회 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('FSA0001', 'FSA', '00', '01', '부채비율', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('FSA0002', 'FSA', '00', '02', '유동비율', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PQA0000', 'PQA', '00', '00', '- 종목별 재무 차트 조회 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PQA0001', 'PQA', '00', '01', '분기', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PQA0002', 'PQA', '00', '02', '연간', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PTV0000', 'PTV', '00', '00', '- 기간별 거래량 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PTV0001', 'PTV', '00', '01', '주', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PTV0002', 'PTV', '00', '02', '월', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('PTV0003', 'PTV', '00', '03', '년', 3);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0000', 'TVB', '00', '00', '- 종목별 일별 거래량 조회 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0001', 'TVB', '00', '01', '투자자', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0002', 'TVB', '00', '02', '신용', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0003', 'TVB', '00', '03', '대차', 3);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0004', 'TVB', '00', '04', '공매도', 4);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVB0005', 'TVB', '00', '05', 'CFD', 5);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVS0000', 'TVS', '00', '00', '- 종목별 일별 거래량 투자자 조회 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVS0001', 'TVS', '00', '01', '투자자별', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('TVS0002', 'TVS', '00', '02', '기관별', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MTP0000', 'MTP', '00', '00', '- 회원 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MTP0001', 'MTP', '00', '01', '일반회원', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MST0000', 'MST', '00', '00', '- 회원 상태', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MST0001', 'MST', '00', '01', '인증대기', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MST0002', 'MST', '00', '02', '인증완료', 2);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MST0003', 'MST', '00', '03', '정지', 3);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('MST0004', 'MST', '00', '04', '탈퇴', 4);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('ETP0000', 'ETP', '00', '00', '- 메일 구분', 0);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('ETP0001', 'ETP', '00', '01', '회원가입 인증', 1);
INSERT INTO em_stock.code (code, first_code, second_code, third_code, code_value, seq) VALUES ('ETP0002', 'ETP', '00', '02', '비밀번호 찾기', 2);

-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('생명과학 및 제약','유전자 치료제/분석,바이오시밀러(복제 바이오의약품),면역항암제,비만치료제,구충제(펜벤다졸/이버멕틴 등),줄기세포,제대혈,마리화나(대마),제약업체,마이크로바이옴',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('의료기술','의료AI,원격진료/비대면진료(U-Healthcare),의료기기,미용기기,치아 치료(임플란트 등),치매,탈모 치료,보톡스(보툴리눔톡신)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('에너지 및 환경','풍력에너지,태양광에너지,수소차(연료전지/부품/충전소),고체산화물 연료전지(SOFC),원자력발전,온실가스(탄소배출권),4대강 복원,LNG(액화천연가스),LPG(액화석유가스),셰일가스(Shale Gas),폐기물처리,수자원(양적/질적 개선),핵융합에너지,폐기물 재활용,황사/미세먼지,겨울,여름,태풍 및 장마,조림사업,자원개발',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('전기차 및 배터리','전기차,2차전지(LFP/리튬인산철),2차전지(전고체),2차전지(생산),전기차(충전소/충전기),폐배터리,2차전지,2차전지(소재/부품)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('반도체 및 디스플레이','반도체 장비,시스템반도체,HBM(고대역폭메모리),3D 낸드(NAND),OLED,마이크로 LED,MLCC(적층세라믹콘덴서),반도체 재료/부품,반도체 대표주(생산),2차전지(소재/부품),2차전지(장비),유리 기판,LED장비,전자파,뉴로모픽 반도체,PCB(FPCB 등),냉각시스템(액침냉각 등)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('스마트 기기 및 모바일','스마트폰,갤럭시 부품주,폴더블폰,아이폰,휴대폰 부품,카메라모듈/부품,모바일솔루션,모바일게임(스마트폰),터치패널(스마트폰/태블릿PC 등),무선충전기술,CCTV＆DVR',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('통신 및 네트워크','5G(5세대 이동통신),통신장비,스마트그리드(지능형전력망),양자암호,NI(네트워크 통합),제4이동통신,RFID(NFC 등),SI(시스템통합),스마트홈(홈네트워크),통신,인터넷 대표주',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('IT 및 AI 기술','클라우드 컴퓨팅,AI 챗봇(챗GPT 등),지능형로봇/인공지능(AI),온디바이스 AI,CXL(컴퓨트익스프레스링크),스마트팩토리(스마트공장),사물인터넷,음성인식,바이오인식(생체인식),가상현실(VR),IT 대표주,증강현실(AR)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('자동차','자율주행차,자동차부품,렌터카,자동차 대표주,타이어',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('인프라','해저터널(지하화/지하도로),GTX(수도권 광역급행철도),우크라이나 재건,남북경협,철도',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('소비재 및 유통','화장품,패션/의류,여행,주류업(주정/에탄올),건강기능식품,편의점,백화점,쿠팡(Coupang),마켓컬리(Kurly),야놀자(Yanolja),면세점,홈쇼핑,소매유통,종합상사',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('금융서비스 및 핀테크','전자결제(전자화폐),핀테크(FinTech),삼성페이,애플페이,가상화폐(비트코인 등),NFT(대체불가토큰),STO(토큰증권 발행),마이데이터, 토스(Toss),인터넷은행,카카오뱅크,지주,은행,두나무(Dunamu),블록체인',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('보험','손해보험,생명보험',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('질병 및 의료 진단','코로나19(진단/치료제/백신),코로나19(진단키트),메르스 코로나 바이러스,백신/진단시약,mRNA(메신저 리보핵산),슈퍼박테리아,엠폭스(원숭이두창),마이코플라스마 폐렴,백신/진단시약/방역(신종플루,AI 등),화이자(PFIZER),구제역/광우병 수혜,아프리카 돼지열병(ASF),모더나(MODERNA),백신여권',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('방위산업 및 안전','방위산업/전쟁 및  테러,재난/안전(지진 등),보안주(물리),보안주(정보),DMZ 평화공원,선박평형수 처리장치',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('농업 및 식품','수산,육계,사료,음식료업종,비료,요소수,농업',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('원자력 및 화학','원자력발전,원자력발전소 해체,석유화학,탄소나노튜브(CNT),페라이트,희귀금속(희토류),니켈,리튬,윤활유,냉각시스템(액침냉각 등)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('교육 및 일자리','교육/온라인 교육,일자리(취업),재택근무/스마트워크,창투사,엔젤산업,기업인수목적회사(SPAC),4차산업 수혜주,2024 상반기 신규상장,2024 하반기 신규상장',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('복지 및 정책','출산장려정책,고령화 사회(노인복지),네옴시티,日 수출 규제(국산화 등),日제품 불매운동(수혜)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('가전 및 생활용품','밥솥,제습기,공기청정기,마스크,리모델링/인테리어,소모성자재구매대행(MRO),제지,',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('3D 및 첨단 제조','3D 프린터,공작기계,2차전지 장비,플렉서블 디스플레이,그래핀,초전도체,로봇(산업용/협동로봇 등),맥신(MXene),골판지 제조',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('전력 및 설비','전력설비,전선,전력저장장치(ESS)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('모빌리티 및 항공','조선,해운,우주항공산업(누리호/인공위성 등),UAM(도심항공모빌리티),리비안(RIVIAN),항공기 부품,남-북-러 가스관사업,항공/저가 항공사(LCC)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('섬유 및 의류','화학섬유,의류,패션,재질 혁신',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('스포츠 및 레저','골프,스포츠행사 수혜(올림픽/월드컵 등),자전거,전기자전거,캐릭터상품,카지노,드론(Drone)',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('디지털화 및 자동화','화폐/금융 자동화기기,키오스크(KIOSK),RFID,스마트카(SMART CAR),자동화 설비',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('미디어 및 콘텐츠','미디어(방송/신문),OTT 서비스,SNS(소셜네트워크서비스),웹툰,영화,게임,모바일게임,엔터테인먼트,영상콘텐츠,모바일콘텐츠(스마트폰/태블릿PC),메타버스(Metaverse),음원/음반,광고,테마파크',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('건설 및 장비','건설기계,조선기자재,피팅(관이음쇠)/밸브,시멘트/레미콘,철강,강관업체(Steel pipe),모듈러주택,건설 중소형,건설 대표주,철강 주요종목,아스콘(아스팔트 콘크리트),철강 중소형,비철금속,페인트',now());
-- INSERT INTO em_stock.theme_category (theme_name,theme_list,create_date) VALUES ('종합 물류,폐기물처리,콜드체인(저온유통),도시가스,LNG',now());